### ISSUE TITLE
MAX nesting level reached aborting error

### ISSUE THREAD

**Issue by OverlanAI** [Program-O/Program-O#449]
https://stackoverflow.com/questions/8656089/
If your getting nesting level errors.
I think this may explain a lot when it comes to WAMP anyway.
I see this sometimes running program O but did not know what the error meant until now.
Anyway its worth looking at if you are seeing it a a lot.
TNX

**Comment by OverlanAI** [comment]
`[30-Aug-2018 12:05:05 America/Detroit] PHP Fatal error:  Uncaught Error: Maximum function nesting level of '256' reached, aborting! in H:\wamp64\www\ProgramO\library\error_functions.php:67
Stack trace:
#0 H:\wamp64\www\ProgramO\chatbot\core\aiml\parse_aiml_as_XML.php(1493): runDebug('H:\\wamp64\\www\\P...', 'tag_to_string', 1493, 'converting the ...', 2)
#1 H:\wamp64\www\ProgramO\chatbot\core\aiml\parse_aiml_as_XML.php(766): tag_to_string(Array, Object(SimpleXMLElement), 'srai', 1, 'element')
#2 H:\wamp64\www\ProgramO\chatbot\core\aiml\parse_aiml_as_XML.php(231): parse_srai_tag(Array, Object(SimpleXMLElement), 'srai', 1)
#3 H:\wamp64\www\ProgramO\chatbot\core\aiml\parse_aiml_as_XML.php(259): parseTemplateRecursive(Array, Object(SimpleXMLElement), 1)
#4 H:\wamp64\www\ProgramO\chatbot\core\aiml\parse_aiml.php(457): parseTemplateRecursive(Array, Object(SimpleXMLElement))
#5 H:\wamp64\www\ProgramO\chatbot\core\aiml\parse_aiml_as_XML.php(770): run_srai(Array, 'are you sure')
#6 H:\wamp64\www\ProgramO\chatbot\core\aiml\parse_aiml_as_XML.php(231): parse_srai_tag(Array, Ob in H:\wamp64\www\ProgramO\library\error_functions.php on line 67`

Forgot to include one of the errors in the log.
tnx

**Comment by OverlanAI** [comment]
UPDATE: Found this occurs when in multi-bot mode where each bot has some SRAI calls of its own.
After i cleared the other bots of there AIML the error stopped.
So i am just running the primary bot for now.
I dont know if that helps any or not.
TNX

**Comment by OverlanAI** [comment]
When i have more bots it is adding to the numbers of Nesting levels it is working with at the same time.
So actually by having more bots just hits the MAX faster or more often as a side effect.
That does not mean that Multi-bots only cause the problem it just happens to amp it up making it worse.

I still have no idea how to fix the problem but at least now i can name the pain better.
TNX

**Comment by OverlanAI** [comment]
On a deeper look (old logs and new ones) It reports one of 2 files JIT blames,
parse_aiml.php (less offten blamed) and parse_aiml_as_xml.php (quite offten).
Mostly when it is processing many TAGS but the actual errors all tend to point to a bad array pointer.
The arrays become empty or not made yet because the JIT steps in and tries to keep it from crashing php.
So that is in the logs is not wrong exactly but is quite misleading as to the cause.
Additional debugging should be added to these areas in order to find what part is actually causing JIT to go off.

TNX (Names the pain and it is Max Nesting Level).

**Comment by OverlanAI** [comment]
changing and or adding to php.ini
; Maximum input variable nesting level
 ; http://php.net/max-input-nesting-level 
max_input_nesting_level = 512 
xdebug.max_nesting_level=512
Does cover the error but as stated in stackoverflow, it is not a good idea because it leads to the following problem.
`PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) in H:\wamp64\www\ProgramO\chatbot\core\aiml\parse_aiml_as_XML.php on line 1503`
That is worse and you do not want to extend that as well (gremlins will get you).
First if you look at the error it does not make since given i have allowed for the max of 1g and it is saying what it wants to use is far far less. Also note the file where this happens at consistently.
I am posting this new error to both show why this is bad idea and also to help narrow down the possible problem areas.
And yes i did change the settings in the global_config so it knows it can use up to 1g but the error seems to not know it can or something lol.
Anyway because i had the first error that now leads to the new one the folks on stackoverflow all say there is a big problem in the code.
TNX

**Comment by OverlanAI** [comment]
get on crew man, with mit and this is nothing but you got to get more pro.

**Comment by OverlanAI** [comment]
you want it then fix it!
